{{- if eq .Values.harbor.enabled true -}}
# Source: cluster-resources/charts/harbor/templates/registry/registry-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "vessl-harbor-registry"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - name: http-registry
      port: 5000

    - name: http-controller
      port: 8080
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: registry
{{- end -}}