{{- $jobservice := .Values.persistence.persistentVolumeClaim.jobservice -}}
{{- if and .Values.persistence.enabled (not $jobservice.existingClaim) (has "file" .Values.jobservice.jobLoggers) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "harbor.jobservice" . }}
  annotations:
  {{- range $key, $value := $jobservice.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: jobservice
spec:
  accessModes: 
    - {{ $jobservice.accessMode }}
  resources:
    requests:
      storage: {{ $jobservice.size }}
  storageClassName: vessl-local-path-{{- .Release.Namespace }}
{{- end }}
