agent:
  accessToken:
  ingressEndpoint:
  providerType: on-premise
  localStorageClassName:
  apiServer: https://api.vessl.ai
  logLevel: info
  env: prod
  image: public.ecr.aws/vessl/cluster-agent:0.5.2
  sentryDsn: https://0481c31171114c109ac911ac947f0518@o386227.ingest.sentry.io/5585090
  manageAllNamespaces: true
  containerLogPath: /var/lib/docker/containers
  containerLogFormat: json

nvidiaDevicePlugin:
  deviceListStrategy: envvar

localPathProvisioner:
  hostPath: /opt/local-path-provisioner
  image: public.ecr.aws/vessl/local-path-provisioner:v0.0.20
  helperImage: public.ecr.aws/vessl/busybox:21.10
  provisionerName: rancher.io/local-path

metricsExporters:
  dcgmExporterUseDeviceName:

tolerations:
- key: CriticalAddonsOnly
  operator: Exists

preinstalledNamespace:
