savvihub:
  agentAccessToken:
  apiServer: https://api.savvihub.com
  logLevel: info
  env: prod
  image: public.ecr.aws/o8g9a7x3/cluster-agent:latest
  sentryDsn: https://0481c31171114c109ac911ac947f0518@o386227.ingest.sentry.io/5585090
  manageAllNamespaces: false
  deviceListStrategy: envvar

kubernetes:
  logContainerPath: /var/lib/docker/containers

localPathProvisioner:
  hostPath: /opt/local-path-provisioner
  image: rancher/local-path-provisioner:v0.0.20
  helperImage: public.ecr.aws/o8g9a7x3/busybox:latest

metricsExporters:
  dcgmExporterUseDeviceName:

tolerations:
- key: CriticalAddonsOnly
  operator: Exists

preinstalledNamespace:
