{{- if eq .Values.harbor.enabled true -}}
# Source: cluster-resources/charts/harbor/templates/jobservice/jobservice-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vessl-harbor-jobservice
  annotations:
    helm.sh/resource-policy: keep
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: jobservice
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vessl-local-path-vessl
{{- end -}}