{{- if eq .Values.harbor.enabled true -}}
# Source: cluster-resources/charts/harbor/templates/jobservice/jobservice-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "vessl-harbor-jobservice"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  JOBSERVICE_SECRET: {{ (randAlphaNum 16) | b64enc | quote }}
  REGISTRY_CREDENTIAL_PASSWORD: {{ template "harbor.registry.password" . }}
{{- end -}}