{{- if .Values.gfd.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vessl-gpu-feature-discovery
  labels:
    app.kubernetes.io/name: vessl-gpu-feature-discovery
    app.kubernetes.io/version: {{.Values.gfd.image.tag}}
    v1.k8s.vessl.ai/managed: 'true'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vessl-gpu-feature-discovery
      app.kubernetes.io/version: {{.Values.gfd.image.tag}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vessl-gpu-feature-discovery
        app.kubernetes.io/version: {{.Values.gfd.image.tag}}
    spec:
      containers:
        - image: {{.Values.gfd.image.repository}}:{{.Values.gfd.image.tag}}
          name: gpu-feature-discovery
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: dmi-product-name
              mountPath: "/sys/class/dmi/id/product_name"
            - name: device-plugin
              mountPath: /device-plugin
            - name: dev
              mountPath: /dev
            - name: nvidia
              mountPath: /usr/local/nvidia
            - name: pod-resources
              mountPath: /var/lib/kubelet/pod-resources
            - name: proc
              mountPath: /proc
            - name: nvidia-config
              mountPath: /etc/nvidia

          securityContext:
            privileged: true
          env:
            - name: MIG_STRATEGY
              value: none
      nodeSelector:
        feature.node.kubernetes.io/pci-10de.present: "true" # NVIDIA vendor ID
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: dmi-product-name
          hostPath:
            path: "/sys/class/dmi/id/product_name"
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
            type: Directory
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
            type: Directory
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: nvidia-config
          hostPath:
            path: /etc/nvidia
            type: DirectoryOrCreate
        - name: nvidia
          hostPath:
            path: /home/kubernetes/bin/nvidia
            type: Directory
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
{{ toYaml .Values.tolerations | indent 8 }}

{{- end -}}
