apiVersion: v1
kind: Secret
metadata:
  name: vessl-prometheus-scrape-config
  labels:
    prometheus: vessl-prometheus
stringData:
  additonal-scrape-config.yaml: |-
    - job_name: 'kubernetes-nodes-cadvisor'
      # Default to scraping over https. If required, just disable this or change to
      # `http`.
      scheme: https

      # This TLS & bearer token file config is used to connect to the actual scrape
      # endpoints for cluster components. This is separate to discovery auth
      # configuration because discovery & scraping are two separate concerns in
      # Prometheus. The discovery auth config is automatic if Prometheus runs inside
      # the cluster. Otherwise, more config options have to be provided within the
      # <kubernetes_sd_config>.
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        # If your node certificates are self-signed or use a different CA to the
        # master CA, then disable certificate verification below. Note that
        # certificate verification is an integral part of a secure infrastructure
        # so this should only be disabled in a co
        # disable certificate verification by uncommenting the line below.
        #
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
        - role: node

      metric_relabel_configs:
      - source_labels:
        - __name__
        regex: '(container_cpu_usage_seconds_total|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_memory_working_set_bytes|container_fs_usage_bytes|kubelet_running_pod_count|kubelet_running_pods|kubelet_volume_stats_capacity_bytes|kubelet_volume_stats_used_bytes)'
        action: keep
      # This configuration will work only on kubelet 1.7.3+
      # As the scrape endpoints for cAdvisor have changed
      # if you are using older version you need to change the replacement to
      # replacement: /api/v1/nodes/$1:4194/proxy/metrics
      # more info here https://github.com/coreos/prometheus-operator/issues/633
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        - regex: (.*)nvidia_com_gfd_timestamp
          action: labeldrop