apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: vessl-prometheus
  name: vessl-dcgm-servicemonitor
spec:
  endpoints:
  - path: /metrics
    port: metrics
    metricRelabelings:
      - sourceLabels:
          - __name__
        regex: '(DCGM_FI_DEV_SM_CLOCK|DCGM_FI_DEV_MEM_CLOCK|DCGM_FI_DEV_GPU_TEMP|DCGM_FI_DEV_POWER_USAGE|DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION|DCGM_FI_DEV_PCIE_REPLAY_COUNTER|DCGM_FI_DEV_GPU_UTIL|DCGM_FI_DEV_MEM_COPY_UTIL|DCGM_FI_DEV_ENC_UTIL|DCGM_FI_DEV_DEC_UTIL|DCGM_FI_DEV_XID_ERRORS|DCGM_FI_DEV_POWER_VIOLATION|DCGM_FI_DEV_THERMAL_VIOLATION|DCGM_FI_DEV_SYNC_BOOST_VIOLATION|DCGM_FI_DEV_BOARD_LIMIT_VIOLATION|DCGM_FI_DEV_LOW_UTIL_VIOLATION|DCGM_FI_DEV_RELIABILITY_VIOLATION|DCGM_FI_DEV_FB_FREE|DCGM_FI_DEV_FB_USED|DCGM_FI_DEV_ECC_SBE_VOL_TOTAL|DCGM_FI_DEV_ECC_DBE_VOL_TOTAL|DCGM_FI_DEV_ECC_SBE_AGG_TOTAL|DCGM_FI_DEV_ECC_DBE_AGG_TOTAL|DCGM_FI_DEV_RETIRED_SBE|DCGM_FI_DEV_RETIRED_DBE|DCGM_FI_DEV_RETIRED_PENDING|DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL)'
        action: keep
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      v1.k8s.vessl.ai/type: dcgm-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: vessl-prometheus
  name: vessl-kube-state-metrics-servicemonitor
spec:
  endpoints:
  - path: /metrics
    port: metrics
    metricRelabelings:
      - sourceLabels:
          - __name__
        regex: '(kube_pod_container_resource_requests|kube_pod_container_resource_limits|kube_node_status_capacity)'
        action: keep
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      v1.k8s.vessl.ai/type: kube-state-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: vessl-prometheus
  name: vessl-node-exporter-servicemonitor
spec:
  endpoints:
  - path: /metrics
    port: metrics
    metricRelabelings:
      - sourceLabels:
          - __name__
        regex: '(node_cpu_seconds_total|node_memory_MemTotal_bytes|node_memory_MemFree_bytes|node_memory_Buffers_bytes|node_memory_Cached_bytes|node_filesystem_size_bytes|node_filesystem_avail_bytes)'
        action: keep
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      v1.k8s.vessl.ai/type: node-exporter