{{- if eq .Values.simpleRegistry.enabled true -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  serviceName: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      {{- with .Values.simpleRegistry.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      nodeSelector:
        node.k0sproject.io/role: control-plane
      {{- with .Values.simpleRegistry.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
      - name: registry
        image: registry:2.8.1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry
      volumes:
      - name: registry
        persistentVolumeClaim:
          claimName: registry
  volumeClaimTemplates:
  - metadata:
      name: registry
    spec:
      accessModes:
      - ReadWriteOnce
      {{- with .Values.simpleRegistry.storageClassName }}
      storageClassName: {{ .Values.simpleRegistry.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: 1Gi
      selector:
        matchLabels:
          app: registry
{{- end -}}
