apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: savvihub-agent
spec:
  selector:
    matchLabels:
      name: savvihub-agent
  template:
    metadata:
      labels:
        name: savvihub-agent
    spec:
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
        - name: savvihub-agent
          image: {{ .Values.savvihub.image }}
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: SAVVIHUB_ENV
              value: {{ .Values.savvihub.env }}
            - name: SAVVIHUB_API_URL
              value: {{ .Values.savvihub.apiServer }}
            - name: SAVVIHUB_LOG_LEVEL
              value: {{ .Values.savvihub.logLevel }}
            - name: SAVVIHUB_SENTRY_DSN
              value: {{ .Values.savvihub.sentryDsn }}
            - name: SAVVIHUB_COLLECT_ALL_NAMESPACE
              value: "{{ .Values.savvihub.manageAllNamespaces }}"
            - name: SAVVIHUB_PREINSTALLED_NAMESPACE
              value: {{ .Values.preinstalledNamespace }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: logcontainerpath
              readOnly: true
              mountPath: {{ .Values.kubernetes.logContainerPath }}
            - name: access-token
              readOnly: true
              mountPath: /secrets
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: logcontainerpath
          hostPath:
            path: {{ .Values.kubernetes.logContainerPath }}
        - name: access-token
          secret:
            secretName: savvihub-agent
      serviceAccountName: savvihub
