{{- if eq .Values.harbor.enabled true -}}
# Source: cluster-resources/charts/harbor/templates/database/database-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "vessl-harbor-database"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 5432
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: database
{{- end -}}