{{- if .Values.metricsExporters.dcgmExporter.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: vessl-dcgm-exporter
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: {{ .Values.metricsExporters.dcgmExporter.imageVersion }}
    v1.k8s.savvihub.com/managed: 'true'
    v1.k8s.savvihub.com/type: dcgm-exporter
    v1.k8s.vessl.ai/managed: 'true'
    v1.k8s.vessl.ai/type: dcgm-exporter
spec:
  selector:
    name: dcgm-exporter
    v1.k8s.vessl.ai/managed: 'true'
  ports:
    - name: metrics
      port: 9400
{{- end -}}
