{{- if empty .Values.preinstalledNamespace -}}
apiVersion: v1
kind: Service
metadata:
  name: savvihub-dcgm-exporter
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 2.1.1
    v1.k8s.savvihub.com/managed: 'true'
    v1.k8s.savvihub.com/type: dcgm-exporter
spec:
  selector:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 2.1.1
  ports:
    - name: metrics
      port: 9400
{{- end -}}
