#{{- if empty .Values.preinstalledNamespace -}}
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: {{ .Release.Name }}-mysql
#  labels:
#    app: {{ .Release.Name }}-mysql
#    env: dev
#spec:
#  selector:
#    matchLabels:
#      app: {{ .Release.Name }}-mysql
#      env: dev
#  template:
#    metadata:
#      name: "mysql"
#      labels:
#        app: {{ .Release.Name }}-mysql
#        env: dev
#    spec:
#      volumes:
#        - name: storage
#          persistentVolumeClaim:
#            claimName: {{ .Release.Name }}-mysql
#      containers:
#        - name: "mysql"
#          image: "mysql:8.0.25"
#          ports:
#            - containerPort: 3306
#          resources:
#            requests:
#              cpu: 100m
#              memory: 128Mi
#          volumeMounts:
#            - name: storage
#              mountPath: /var/lib/mysql
#              subPath: mysql
#          env:
#            - name: MYSQL_ROOT_PASSWORD
#              value: "{{ .Values.mysql.rootPassword }}"
#            - name: MYSQL_USER
#              value: "{{ .Values.mysql.user }}"
#            - name: MYSQL_PASSWORD
#              value: "{{ .Values.mysql.password }}"
#            - name: MYSQL_DATABASE
#              value: "aron"
#  {{- end -}}