apiVersion: apps/v1
kind: Deployment
metadata:
  name: vessl-cluster-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vessl-cluster-agent
  template:
    metadata:
      labels:
        name: vessl-cluster-agent
        v1.k8s.savvihub.com/logs-enabled: 'true'
        v1.k8s.savvihub.com/type: agent
        v1.k8s.vessl.ai/logs-enabled: 'true'
        v1.k8s.vessl.ai/type: agent
    spec:
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      tolerations:
{{ toYaml .Values.agent.tolerations | indent 8 }}
      containers:
        - name: vessl-cluster-agent
{{ if .Values.agent.customImageSource }}
          image: {{ .Values.agent.customImageSource }}
{{ else }}
          image: {{ template "vessl.image.source" . -}}/cluster-agent:{{- .Values.agent.imageVersion }}
{{ end }}
          imagePullPolicy: {{ .Values.agent.imagePullPolicy }}
          args:
            - "cluster"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: VESSL_ENV
              value: "{{ .Values.agent.env }}"
            {{- if .Values.agent.clusterName }}
            - name: VESSL_CLUSTER_NAME
              value: "{{ .Values.agent.clusterName }}"
            {{- end }}
            - name: VESSL_API_URL
              value: "{{ .Values.agent.apiServer }}"
            - name: VESSL_LOG_LEVEL
              value: "{{ .Values.agent.logLevel }}"
            - name: VESSL_SENTRY_DSN
              value: "{{ .Values.agent.sentryDsn }}"
            - name: VESSL_HELM_RELEASE_NAME
              value: "{{ .Release.Name }}"
            - name: VESSL_KUBERNETES_INGRESS_ENDPOINT
              value: "{{ .Values.agent.ingressEndpoint }}"
            - name: VESSL_PROVIDER_TYPE
              value: "{{ .Values.agent.providerType }}"
            - name: VESSL_LOCAL_STORAGE_CLASS_NAME
              {{- if .Values.agent.localStorageClassName }}
              value: "{{ .Values.agent.localStorageClassName }}"
              {{- else }}
              value: "vessl-local-path-{{ .Release.Namespace }}"
              {{- end }}
          volumeMounts:
            - name: access-token
              readOnly: true
              mountPath: /secrets
      terminationGracePeriodSeconds: 30
      volumes:
        - name: access-token
          secret:
            secretName: vessl-agent
      serviceAccountName: vessl
