apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vessl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vessl
subjects:
  - kind: ServiceAccount
    name: vessl
    namespace: {{ .Release.Namespace }}
