kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vessl
subjects:
  - kind: ServiceAccount
    name: vessl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vessl

{{- if not (empty .Values.preinstalledNamespace) }}
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vessl-exporters
  namespace: {{ .Values.preinstalledNamespace }}
subjects:
  - kind: ServiceAccount
    name: vessl
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vessl-exporters
{{- end -}}
