{{- if eq .Values.harbor.enabled true -}}
# Source: cluster-resources/charts/harbor/templates/setup-job/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-harbor
spec:
  template:
    spec:
      containers:
        - name: setup-harbor
          image: quay.io/vessl-ai/setup-harbor-for-vessl:latest
          command:
            - /setup-harbor
          env:
            - name: HARBOR_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vessl-harbor-core
                  key: HARBOR_ADMIN_PASSWORD
                  optional: false
      restartPolicy: OnFailure
      {{- with .Values.harbor.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.harbor.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end -}}
